services:
  db:
    image: pshaddel/postgres-pgtap:18
    container_name: pgsql_db
    ports:
      - "127.0.0.1:${POSTGRES_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${PGUSER:-postgres}
      POSTGRES_PASSWORD: ${PGPASSWORD:-postgres}
      POSTGRES_DB: ${PGDATABASE:-ledger}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 15

  migrate:
    image: arigaio/atlas:latest
    container_name: atlas_migrate
    depends_on:
      db:
        condition: service_healthy
    working_dir: /workspace
    volumes:
      - ./schema:/workspace/migrations
      - ./atlas.hcl:/workspace/atlas.hcl:ro
    environment:
      ATLAS_LOG_FORMAT: ${ATLAS_LOG_FORMAT:-cli}
    command: ["migrate", "apply", "--env", "docker"]
    restart: "no"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  hash:
    image: arigaio/atlas:latest
    container_name: atlas_hash
    profiles:
      - manual
    depends_on:
      db:
        condition: service_healthy
    working_dir: /workspace
    volumes:
      - ./schema:/workspace/migrations
      - ./atlas.hcl:/workspace/atlas.hcl
    environment:
      ATLAS_LOG_FORMAT: ${ATLAS_LOG_FORMAT:-cli}
    command: ["migrate", "hash"]
    restart: "no"

  pgtap:
    image: pshaddel/postgres-pgtap:18
    container_name: pgtap
    profiles:
      - manual
    depends_on:
      hash:
        condition: service_completed_successfully
      migrate:
        condition: service_completed_successfully
    environment:
      PGHOST: db
      PGUSER: ${POSTGRES_USER:-postgres}
      PGPASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATABASE: ${POSTGRES_DB:-ledger}
    volumes:
      - ./PGTap:/tests
    entrypoint: >
      sh -c "psql -c 'CREATE EXTENSION IF NOT EXISTS pgtap;' && pg_prove /tests/*.sql"

volumes:
  db_data:
  pgadmin_data:
